"""add max weight record

Revision ID: 050cdbf56664
Revises: 64678ab4ba9a
Create Date: 2025-09-15 11:52:10.847828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '050cdbf56664'
down_revision: Union[str, Sequence[str], None] = '64678ab4ba9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('max_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(scale=2), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exercises', sa.Column('max_weight_id', sa.Integer(), nullable=True))
    op.alter_column('exercises', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'exercises', 'max_weights', ['max_weight_id'], ['id'])
    op.alter_column('routines_exercises_sets', 'targeted_weight',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(scale=2),
               nullable=True)
    op.alter_column('routines_exercises_sets', 'targeted_reps',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(scale=2),
               nullable=True)
    op.alter_column('sessions_exercises', 'weight_lifted',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(scale=2),
               nullable=True)
    op.alter_column('sessions_exercises', 'reps_completed',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions_exercises', 'reps_completed',
               existing_type=sa.Numeric(scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions_exercises', 'weight_lifted',
               existing_type=sa.Numeric(scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('routines_exercises_sets', 'targeted_reps',
               existing_type=sa.Numeric(scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('routines_exercises_sets', 'targeted_weight',
               existing_type=sa.Numeric(scale=2),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.alter_column('exercises', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exercises', 'max_weight_id')
    op.drop_table('max_weights')
    # ### end Alembic commands ###
