"""update cascade delete on workout session

Revision ID: 64678ab4ba9a
Revises: 7f28a6618156
Create Date: 2025-09-11 12:35:30.027898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64678ab4ba9a'
down_revision: Union[str, Sequence[str], None] = '7f28a6618156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_exercises_session_id_fkey'), 'sessions_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'sessions_exercises', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions_exercises', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_exercises_session_id_fkey'), 'sessions_exercises', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
