"""update max_weight table to hold session exercise id

Revision ID: 7b6e49b97f6c
Revises: ba397b41bf3d
Create Date: 2025-09-15 17:49:34.199658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b6e49b97f6c'
down_revision: Union[str, Sequence[str], None] = 'ba397b41bf3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('max_weights', sa.Column('session_exercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'max_weights', 'sessions', ['session_exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'max_weights', type_='foreignkey')
    op.drop_column('max_weights', 'session_exercise_id')
    # ### end Alembic commands ###
