"""update optioanl foreign key

Revision ID: 7f28a6618156
Revises: b8ed39a544bc
Create Date: 2025-09-09 15:02:08.282229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f28a6618156'
down_revision: Union[str, Sequence[str], None] = 'b8ed39a544bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routines_exercises_sets', 'routine_exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routines_exercises_sets', 'routine_exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
