"""add super user

Revision ID: 8ac1172e680b
Revises: 470518bfe0bb
Create Date: 2025-10-06 15:17:11.712115

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String, Float
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ac1172e680b'
down_revision: Union[str, Sequence[str], None] = '470518bfe0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = table(
        "users",
        column("username", String),
        column("created_at", Float),
        column("updated_at", Float)
    )
    op.bulk_insert(user_table, [{
        'username': 'admin', 'created_at': 0, 'updated_at': 0
    }])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = table(
        "users",
        column("username", String),
        column("created_at", Float),
        column("updated_at", Float)
    )
    op.execute(
        user_table.delete().where(user_table.c.username == 'admin')
    )
    # ### end Alembic commands ###
