"""update session routine table order column with nullable

Revision ID: 8f17319990c1
Revises: b25a9a2d5ea1
Create Date: 2025-08-22 16:10:58.894705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f17319990c1"
down_revision: Union[str, Sequence[str], None] = "b25a9a2d5ea1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions_exercises", sa.Column("order", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions_exercises", "order")
    # ### end Alembic commands ###
