"""update something

Revision ID: 933eb80a3da6
Revises: 8f17319990c1
Create Date: 2025-08-22 17:47:46.102292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "933eb80a3da6"
down_revision: Union[str, Sequence[str], None] = "8f17319990c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions_routines")
    op.alter_column("routines", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column("sessions", sa.Column("routine_id", sa.Integer(), nullable=True))
    op.add_column("sessions", sa.Column("updated_at", sa.Float(), nullable=True))
    op.alter_column("sessions", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "sessions", "routines", ["routine_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.alter_column("sessions", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("sessions", "updated_at")
    op.drop_column("sessions", "routine_id")
    op.alter_column("routines", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_table(
        "sessions_routines",
        sa.Column("session_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("routine_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["routine_id"],
            ["routines.id"],
            name=op.f("sessions_routines_routine_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("sessions_routines_session_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "session_id", "routine_id", name=op.f("sessions_routines_pkey")
        ),
    )
    # ### end Alembic commands ###
