"""update session routine table created at

Revision ID: b25a9a2d5ea1
Revises: 47a2cfc2b935
Create Date: 2025-08-22 15:40:45.748007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b25a9a2d5ea1"
down_revision: Union[str, Sequence[str], None] = "47a2cfc2b935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions_routines", sa.Column("created_at", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions_routines", "created_at")
    # ### end Alembic commands ###
