"""update table again

Revision ID: b8ed39a544bc
Revises: 933eb80a3da6
Create Date: 2025-08-26 15:14:34.535955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b8ed39a544bc"
down_revision: Union[str, Sequence[str], None] = "933eb80a3da6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions_exercises",
        sa.Column("set_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_constraint(
        op.f("sessions_exercises_routines_exercises_sets_id_fkey"),
        "sessions_exercises",
        type_="foreignkey",
    )
    op.drop_column("sessions_exercises", "routines_exercises_sets_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions_exercises",
        sa.Column(
            "routines_exercises_sets_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("sessions_exercises_routines_exercises_sets_id_fkey"),
        "sessions_exercises",
        "routines_exercises_sets",
        ["routines_exercises_sets_id"],
        ["id"],
    )
    op.drop_column("sessions_exercises", "set_type")
    # ### end Alembic commands ###
