"""update max weight record

Revision ID: df11c34d4e17
Revises: 050cdbf56664
Create Date: 2025-09-15 12:05:39.691724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df11c34d4e17'
down_revision: Union[str, Sequence[str], None] = '050cdbf56664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercises_max_weight_id_fkey'), 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'max_weight_id')
    op.drop_constraint(op.f('max_weights_user_id_fkey'), 'max_weights', type_='foreignkey')
    op.drop_constraint(op.f('max_weights_exercise_id_fkey'), 'max_weights', type_='foreignkey')
    op.create_foreign_key(None, 'max_weights', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'max_weights', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'max_weights', type_='foreignkey')
    op.drop_constraint(None, 'max_weights', type_='foreignkey')
    op.create_foreign_key(op.f('max_weights_exercise_id_fkey'), 'max_weights', 'exercises', ['exercise_id'], ['id'])
    op.create_foreign_key(op.f('max_weights_user_id_fkey'), 'max_weights', 'users', ['user_id'], ['id'])
    op.add_column('exercises', sa.Column('max_weight_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('exercises_max_weight_id_fkey'), 'exercises', 'max_weights', ['max_weight_id'], ['id'])
    # ### end Alembic commands ###
