"""Init tables update

Revision ID: f4284e4fd577
Revises: de0b0c43a853
Create Date: 2025-08-20 17:46:20.642934

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f4284e4fd577"
down_revision: Union[str, Sequence[str], None] = "de0b0c43a853"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("routines_exercises_sets_routine_exercise_id_fkey"),
        "routines_exercises_sets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "routines_exercises_sets",
        "routines_exercises",
        ["routine_exercise_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "routines_exercises_sets", type_="foreignkey")
    op.create_foreign_key(
        op.f("routines_exercises_sets_routine_exercise_id_fkey"),
        "routines_exercises_sets",
        "routines_exercises",
        ["routine_exercise_id"],
        ["id"],
    )
    # ### end Alembic commands ###
