"""update relationship

Revision ID: f8281d9c8252
Revises: 7b6e49b97f6c
Create Date: 2025-09-15 18:05:59.373044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8281d9c8252'
down_revision: Union[str, Sequence[str], None] = '7b6e49b97f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('max_weights_session_exercise_id_fkey'), 'max_weights', type_='foreignkey')
    op.create_foreign_key(None, 'max_weights', 'sessions_exercises', ['session_exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'max_weights', type_='foreignkey')
    op.create_foreign_key(op.f('max_weights_session_exercise_id_fkey'), 'max_weights', 'sessions', ['session_exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
